version: '3.8'

services:
  med-friend-db-sql:
    image: postgres:16.2
    container_name: ${CONTAINER_NAME}
    ports:
      - "7500:5432"
    volumes:
      - ./med-friend-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      custom_network:
        ipv4_address: 172.18.0.2

  consul:
    image: consul:1.15.4
    container_name: consul-medfri
    ports:
      - "8500:8500"  # Consul UI
      - "8600:8600"  # Consul DNS
    command: "agent -dev -client 0.0.0.0"
    volumes:
      - ./consul-data:/consul/data
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      custom_network:
        ipv4_address: 172.18.0.8

  redis:
    image: redis:7.0
    container_name: redis-medfriend
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data
    networks:
      custom_network:
        ipv4_address: 172.18.0.3

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-medfriend
    ports:
      - ${RABBIT_PORT}:5672
      - 15672:15672
      - 15674:15674
      - 61613:61613
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp
      && rabbitmq-server"
    networks:
      custom_network:
        ipv4_address: 172.18.0.4

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus-medfriend
    ports:
      - "8081:8081"
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      NEXUS_CONTEXT_PATH: "/"
      NEXUS_SECURITY_RANDOMPASSWORD: "false"
    networks:
      custom_network:
        ipv4_address: 172.18.0.5

  minio:
    image: minio/minio:latest
    container_name: minio-medfriend
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      custom_network:
        ipv4_address: 172.18.0.6

  nginx:
    image: nginx:latest
    container_name: nginx-medfriend
    #ports:
    #  - "80:80"
    #  - "443:443"
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./ssl/nginx.key:/etc/nginx/ssl/nginx.key:ro
    #networks:
    #  custom_network:
    #    ipv4_address: 172.18.0.7

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
