version: '3.8'

services:
  harbor-db:
    image: goharbor/harbor-db:v2.5.0
    container_name: harbor-db
    networks:
      - harbornet
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - harbor-db:/var/lib/postgresql/data
    restart: always

  redis-harbor:
    image: redis:6.0
    container_name: harbor-redis
    networks:
      - harbornet
    restart: always

  harbor-core:
    image: goharbor/harbor-core:v2.5.0
    container_name: harbor-core
    depends_on:
      - harbor-db
      - redis-harbor
    networks:
      - harbornet
    environment:
      CORE_SECRET: harborsecret
      POSTGRESQL_HOST: harbor-db  # Ensure this points to the DB container name
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: root123
    restart: always

  harbor-portal:
    image: goharbor/harbor-portal:v2.5.0
    container_name: harbor-portal
    networks:
      - harbornet
    restart: always

  registry:
    image: goharbor/registry-photon:v2.5.0
    container_name: harbor-registry
    depends_on:
      - redis-harbor
    networks:
      - harbornet
    volumes:
      - ./data/registry:/storage
      - ./common/config/registry/:/etc/registry/
    restart: always

  nginx-harbor:
    image: goharbor/nginx-photon:v2.5.0
    container_name: harbor-nginx
    networks:
      - harbornet
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./data/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  harbor-jobservice:
    image: goharbor/harbor-jobservice:v2.5.0
    container_name: harbor-jobservice
    depends_on:
      - harbor-core
    networks:
      - harbornet
    restart: always

networks:
  harbornet:
    driver: bridge

volumes:
  harbor-db:
  data:
    driver: local
